plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

base {
    archivesName = "forge-${mod_id}-${minecraft_version}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

repositories {
    maven { url = "https://cursemaven.com" }
    maven { url = "https://api.modrinth.com/maven"}
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('../common/src/generated/resources/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    //runtimeOnly "maven.modrinth:connector:1.0.0-beta.46+1.20.1"
    //runtimeOnly "maven.modrinth:forgified-fabric-api:0.92.2+1.11.12+1.20.1"
    //runtimeOnly "maven.modrinth:dye-depot:1.0.3-fabric"
    //modImplementation "maven.modrinth"

    //RUNICLIB
    modImplementation "curse.maven:runiclib-880879:6329449"

    //TESTING
    //implementation "curse.maven:quark-243121:6427817"
    //implementation "curse.maven:zeta-968868:6432578"
    //implementation "curse.maven:supplementaries-412082:6615104"
    //implementation "curse.maven:selene-499980:6693288"
    //implementation "curse.maven:clayworks-592162:6321200"
    //implementation "curse.maven:blueprint-382216:6408581"

    //COMPAT STUFF
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

sourceSets.main.resources { srcDir project(":common").file('src/main/generated/').getAbsolutePath() }
//sourceSets.main.resources.srcDir file('../common/src/main/generated/')
